version: "3.8"

services:
  mongo1:
    image: mongo:8.0
    container_name: mongo1
    ports:
      - 27017:27017
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - ./data/mongo1:/data/db
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:8.0
    container_name: mongo2
    ports:
      - 27018:27017
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - ./data/mongo2:/data/db
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:8.0
    container_name: mongo3
    ports:
      - 27019:27017
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - ./data/mongo3:/data/db
    networks:
      - mongo-cluster
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672        # cổng cho ứng dụng kết nối (AMQP)
      - 15672:15672      # cổng quản trị web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
